spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    name: shipment
    url: jdbc:mysql://127.0.0.1:3306/shipment?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: sl._shipment
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean
server:
  port: 8090